// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LabCoreSoft.API.Models;

public partial class Ciudad
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? IdDepartamento { get; set; }

    public virtual Departamento IdDepartamentoNavigation { get; set; }

    public virtual ICollection<Paciente> Pacientes { get; set; } = new List<Paciente>();
}