// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LabCoreSoft.API.Models;

public partial class Paciente
{
    public int Id { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public int? IdTipoDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public int? IdCiudad { get; set; }

    public virtual Ciudad IdCiudadNavigation { get; set; }

    public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
}