// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LabCoreSoft.API.Models;

public partial class TipoDocumento
{
    public int Id { get; set; }

    public string Tipo { get; set; }

    public virtual Paciente Paciente { get; set; }
}