// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LabCoreSoft.API.Models;

public partial class LabCoreSoftMedicoContext : DbContext
{
    public LabCoreSoftMedicoContext(DbContextOptions<LabCoreSoftMedicoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ciudad> Ciudades { get; set; }

    public virtual DbSet<Departamento> Departamentos { get; set; }

    public virtual DbSet<Paciente> Pacientes { get; set; }

    public virtual DbSet<TipoDocumento> TiposDocumento { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ciudad>(entity =>
        {
            entity.ToTable("Ciudades");

            entity.HasKey(e => e.Id).HasName("PK__Ciudades__3214EC0710A0D17E");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.IdDepartamentoNavigation).WithMany(p => p.Ciudades)
                .HasForeignKey(d => d.IdDepartamento)
                .HasConstraintName("FK__Ciudades__IdDepa__286302EC");
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.ToTable("Departamentos");

            entity.HasKey(e => e.Id).HasName("PK__Departam__3214EC07C6378B6C");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Paciente>(entity =>
        {
            entity.ToTable("Pacientes");

            entity.HasKey(e => e.Id).HasName("PK__Paciente__3214EC0714A3D749");

            entity.HasIndex(e => new { e.IdTipoDocumento, e.NumeroDocumento }, "UC_TipoDocumento_NumeroDocumento").IsUnique();

            entity.Property(e => e.Apellidos)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NumeroDocumento)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdCiudadNavigation).WithMany(p => p.Pacientes)
                .HasForeignKey(d => d.IdCiudad)
                .HasConstraintName("FK__Pacientes__IdCiu__2E1BDC42");

            entity.HasOne(d => d.IdTipoDocumentoNavigation).WithOne(p => p.Paciente)
                .HasForeignKey<Paciente>(d => d.IdTipoDocumento)
                .HasConstraintName("FK__Pacientes__IdCiu__2D27B809");
        });

        modelBuilder.Entity<TipoDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TiposDoc__3214EC079F30FD1B");

            entity.ToTable("TiposDocumento");

            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}